# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "aspyatkin/ubuntu-16.04-server-amd64"          # vagrant专用的虚拟机镜像文件，这一文件可从https://pan.baidu.com/s/1wJCeWEyxKQLVPi1IH1IlYg下载，官网http://www.vagrantbox.es/也提供了许多不同的镜像，
    master.vm.hostname = "master"
    #master.vm.network "private_network", ip: "192.168.33.10"        # 使用虚拟网络，ip可任意指定
	master.vm.network "public_network", bridge: "eth1"               # 使用桥接网络，需要指定宿主机的网卡名称
    master.vm.synced_folder "./share/master", "/home/vagrant/share"  # 指定共享目录，相当于Docker的Volumes，第一个是宿主机的目录，第二个是虚拟机的目录
    master.vm.provider "virtualbox" do |v|                           # 针对VirtualBox软件做的一些设置。如果使用了不同的虚拟机软件，则这里需要修改
      v.gui = false                                                  # 不启动界面。Ubuntu-server本身也是没有图形界面的，启动界面后也只有一个命令行
      v.name = "master"                                              # VirutalBox内给虚拟机起的名字
      v.memory = 4096                                                # 分配的内存，单位是MB
      v.cpus = 2                                                     # 分配的CPU核心数
    end
  end
  # 使用循环定义node节点虚拟机，可任意指定数量
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "aspyatkin/ubuntu-16.04-server-amd64" 
      node.vm.hostname = "node#{i}"
	  node.vm.network "public_network", bridge: "eth1"
      node.vm.synced_folder "./share/node#{i}", "/home/vagrant/share"
      node.vm.provider "virtualbox" do |v|
        v.gui = false
        v.name = "name#{i}"
        v.memory = 4096
        v.cpus = 2
      end
    end
  end
end